#!/bin/bash
SECTORSIZE=512
BOOT1_BINARY_LOCATION=bootloader/boot1.bin
BOOT1_BINARY_FILESIZE=$(stat -c%s "$BOOT1_BINARY_LOCATION")
echo "Size of $BOOT1_BINARY_LOCATION = $BOOT1_BINARY_FILESIZE bytes."
KERNEL_BINARY_LOCATION=kernel/kernel.bin
KERNEL_BINARY_FILESIZE=$(stat -c%s "$KERNEL_BINARY_LOCATION")
echo "Size of $KERNEL_BINARY_LOCATION = $KERNEL_BINARY_FILESIZE bytes."
BOOT1_BINARY_ROUNDUP_SIZE=$((BOOT1_BINARY_FILESIZE+SECTORSIZE))
BOOT1_BINARY_FINAL_SIZE=$((BOOT1_BINARY_ROUNDUP_SIZE/SECTORSIZE))
if [[ "$BOOT1_BINARY_FINAL_SIZE" -gt 1 ]]; then
echo "Sector count for $BOOT1_BINARY_LOCATION = $BOOT1_BINARY_FINAL_SIZE sectors."
else
echo "Sector count for $BOOT1_BINARY_LOCATION = $BOOT1_BINARY_FINAL_SIZE sector."
fi
KERNEL_BINARY_ROUNDUP_SIZE=$((KERNEL_BINARY_FILESIZE+SECTORSIZE))
KERNEL_BINARY_FINAL_SIZE=$((KERNEL_BINARY_ROUNDUP_SIZE/SECTORSIZE))
if [[ "$BOOT1_BINARY_FINAL_SIZE" -gt 1 ]]; then
echo "Sector count for $KERNEL_BINARY_LOCATION = $KERNEL_BINARY_FINAL_SIZE sectors."
else
echo "Sector count for $KERNEL_BINARY_LOCATION = $KERNEL_BINARY_FINAL_SIZE sector."
fi
echo "$KERNEL_BINARY_FINAL_SIZE" > bootloader/boot0.h