#!/bin/bash
KERNEL_BINARY_LOCATION=nucleus/kernel.bin
SECTORSIZE=512
KERNEL_BINARY_FILESIZE=$(stat -c%s "$KERNEL_BINARY_LOCATION")
KERNEL_BINARY_ROUNDUP_SIZE=$((KERNEL_BINARY_FILESIZE+SECTORSIZE))
KERNEL_BINARY_FINAL_SIZE=$((KERNEL_BINARY_ROUNDUP_SIZE/SECTORSIZE))
BOOTLOADER_INCLUDE_FILE=initium/boot1.h

echo "$KERNEL_BINARY_FINAL_SIZE" > $BOOTLOADER_INCLUDE_FILE
sed -i '1s/^/.set I386_KERNEL_SIZE, /' $BOOTLOADER_INCLUDE_FILE